### PR TITLE
Patch 2

### LINKED ISSUE #3: Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files
I got this error on my pipeline, consider upgrade

Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### LINKED ISSUE #4: Node.js 12 actions are deprecated
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16

### PR DESCRIPTION
**Pull request by saniales**
Fixes #3 
Fixes #4 
Replaces #5

### CODE REVIEW

**Comment by saniales** [comment]
After this merge we may need a release upgrade to make it available on github marketplace

**Comment by saniales** [comment]
any news on this?

**Comment by tnishinaga** [comment]
We are very sorry for the delay in responding to you.
 
This PR looks good for us, so we reopen and merge.

Thank you very much for your valuable contribution.

**Review by tnishinaga — APPROVED** [review]

**Comment by saniales** [comment]
We still need to release a new version for this action

**Comment by saniales** [comment]
Please release a new version to allow other people to download the version with the fix, thanks @tnishinaga

**Comment by tnishinaga** [comment]
Thank you for contacting us.
We have released [v1.1.0](https://github.com/Idein/action-s3-cache/releases/tag/v1.1.0).

**Pull request merged**
